import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import firwin, lfilter, freqz
numtaps=121
cuttoff=0.3
h_w_1=firwin(numtaps, cuttoff, window='hamming')
h_w_2=firwin(numtaps, cuttoff, window='hann')
h_w_3=firwin(numtaps, cuttoff, window='boxcar')
h_w_4=firwin(numtaps, cuttoff, window='bartlett')
w1, h1=freqz(h_w_1)
w2, h2=freqz(h_w_2)
w3, h3=freqz(h_w_3)
w4, h4=freqz(h_w_4)
plt.figure(figsize=(10, 8))
plt.subplot(2, 2 ,1)
plt.plot(w1/np.pi, 20 * np.log10(abs(h1)))
plt.title('LPF Freq Response(hamming)')
plt.xlabel('Normalized Freq(rad/sample)')
plt.ylabel('Magnitude(dB)')
plt.grid()
plt.subplot(2, 2 ,2)
plt.plot(w2/np.pi, 20 * np.log10(abs(h2)))
plt.title('LPF Freq Response(hann)')
plt.xlabel('Normalized Freq(rad/sample)')
plt.ylabel('Magnitude(dB)')
plt.grid()
plt.subplot(2, 2, 3)
plt.plot(w3/np.pi, 20 * np.log10(abs(h3)))
plt.title('LPF Freq Response(rectangular)')
plt.xlabel('Normalized Freq(rad/sample)')
plt.ylabel('Magnitude(dB)')
plt.grid()
plt.subplot(2, 2 ,4)
plt.plot(w4/np.pi, 20 * np.log10(abs(h4)))
plt.title('LPF Freq Response(bartlett)')
plt.xlabel('Normalized Freq(rad/sample)')
plt.ylabel('Magnitude(dB)')
plt.grid()
plt.tight_layout()
plt.show()
